 
 
export const metadata = {
  title: "Next demo app",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    //change to body
    <main className="bg-slate-300">
        {children}
    </main>
  );
}
